/**
 * Bit-parity against the Swift reference's SeededRNG.swift.
 *
 * Reference values were generated by a Swift harness and pasted below, so this
 * runs standalone. If the RNG ever drifts from the reference, every render that
 * depends on phase randomisation silently diverges — which is exactly the class
 * of bug that is invisible without a test like this one.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { FastRNG, mixSeed, blockSeed, nextPow2 } from '../src/rng.js';

const BASE = 0x2545f4914f6cdd1dn;

/** Advance a generator `n + 1` times and return the last value. */
function nth(rng, n) {
  let v = 0;
  for (let i = 0; i <= n; i++) v = rng.unit();
  return v;
}

describe('blockSeed', () => {
  // Generated by the Swift harness — do not hand-edit.
  const REF = [
    [0, '578543533230821686'],
    [1, '1021872585515595792'],
    [2, '17680012233655626093'],
    [7, '14656802415308921253'],
    [63, '13842589763943345005'],
    [1000, '3216090030704503598'],
    [123456, '13552240896517669585'],
  ];

  for (const [b, want] of REF) {
    it(`matches Swift for block ${b}`, () => {
      assert.equal(blockSeed(BASE, b).toString(), want);
    });
  }

  it('stays inside 64 bits', () => {
    for (const b of [0, 1, 99, 100000]) {
      const s = blockSeed(BASE, b);
      assert.ok(s >= 0n && s < 1n << 64n, `blockSeed(base, ${b}) out of range`);
    }
  });

  it('decorrelates adjacent blocks', () => {
    // The whole reason for the double mix: a linear seed function leaves
    // neighbouring windows correlated, which is audible as amplitude flutter.
    const a = blockSeed(BASE, 100);
    const b = blockSeed(BASE, 101);
    const diff = a > b ? a - b : b - a;
    assert.ok(diff > 1000000n, 'adjacent block seeds are suspiciously close');
  });

  it('handles a negative index without throwing', () => {
    assert.equal(typeof blockSeed(BASE, -1), 'bigint');
  });
});

describe('mixSeed', () => {
  it('is deterministic', () => {
    assert.equal(mixSeed(42n), mixSeed(42n));
  });

  it('spreads sequential inputs apart', () => {
    const seen = new Set();
    for (let i = 0; i < 64; i++) seen.add(mixSeed(BigInt(i)).toString());
    assert.equal(seen.size, 64);
  });

  it('stays inside 64 bits for a large input', () => {
    const s = mixSeed((1n << 64n) - 1n);
    assert.ok(s >= 0n && s < 1n << 64n);
  });
});

describe('FastRNG', () => {
  // Generated by the Swift harness — [block, drawIndex, expected].
  const REF = [
    [0, 0, 0.85097486776298126], [0, 1, 0.30447531303922404],
    [0, 2, 0.0041088058985444542], [0, 3, 0.52045729208622116],
    [0, 4, 0.66939245016178162], [0, 5, 0.3473700472745056],
    [0, 6, 0.21497154310775046], [0, 7, 0.088279166503864359],
    [1, 0, 0.50647143968786867], [1, 1, 0.18962074836606113],
    [1, 2, 0.64393051747155861], [1, 3, 0.47886966480884796],
    [1, 4, 0.099860195685446462], [1, 5, 0.085978799124741712],
    [1, 6, 0.7922183899731875], [1, 7, 0.022073688005179393],
    [5, 0, 0.77310530947543377], [5, 1, 0.1228715084068589],
    [5, 2, 0.22286641373227811], [5, 3, 0.31931576659956162],
    [5, 4, 0.27671033429406089], [5, 5, 0.73898382640982729],
    [5, 6, 0.86041676975972692], [5, 7, 0.94604228745537622],
  ];

  for (const [block, index, want] of REF) {
    it(`block ${block} draw ${index} matches Swift`, () => {
      const got = nth(new FastRNG(blockSeed(BASE, block)), index);
      assert.equal(got.toPrecision(17), want.toPrecision(17));
    });
  }

  it('remaps a zero seed to the golden-ratio constant', () => {
    // xorshift64 is stuck at zero forever otherwise.
    const REF_ZERO = [
      0.85979412078081652, 0.39430133835633674,
      0.48058787404949177, 0.18894988582774552,
    ];
    const rng = new FastRNG(0n);
    for (let i = 0; i < REF_ZERO.length; i++) {
      assert.equal(rng.unit().toPrecision(17), REF_ZERO[i].toPrecision(17));
    }
  });

  it('stays within [0, 1)', () => {
    const rng = new FastRNG(blockSeed(BASE, 3));
    for (let i = 0; i < 10000; i++) {
      const v = rng.unit();
      assert.ok(v >= 0 && v < 1, `draw ${i} out of range: ${v}`);
    }
  });

  it('is reproducible from the same seed', () => {
    const a = new FastRNG(blockSeed(BASE, 9));
    const b = new FastRNG(blockSeed(BASE, 9));
    for (let i = 0; i < 100; i++) assert.equal(a.unit(), b.unit());
  });

  it('diverges from a different seed', () => {
    const a = new FastRNG(blockSeed(BASE, 9));
    const b = new FastRNG(blockSeed(BASE, 10));
    let same = 0;
    for (let i = 0; i < 100; i++) if (a.unit() === b.unit()) same++;
    assert.equal(same, 0);
  });

  it('has a roughly uniform mean', () => {
    const rng = new FastRNG(blockSeed(BASE, 1));
    let sum = 0;
    const n = 50000;
    for (let i = 0; i < n; i++) sum += rng.unit();
    assert.ok(Math.abs(sum / n - 0.5) < 0.01);
  });
});

describe('nextPow2', () => {
  it('rounds up to the next power of two', () => {
    assert.equal(nextPow2(1000), 1024);
    assert.equal(nextPow2(3), 4);
    assert.equal(nextPow2(11025), 16384);
  });

  it('leaves an exact power of two alone', () => {
    assert.equal(nextPow2(1024), 1024);
    assert.equal(nextPow2(1), 1);
  });

  it('returns 1 for zero and negatives', () => {
    assert.equal(nextPow2(0), 1);
    assert.equal(nextPow2(-5), 1);
  });
});

describe('seed coercion', () => {
  /* The engines hand caller options straight to the RNG. A plain number is the
   * natural thing to pass — the README's option tables just say `DEFAULT_SEED`
   * — and before coercion it surfaced as "Cannot mix BigInt and other types"
   * from inside xorshift, which tells the caller nothing. */
  it('accepts a number and a bigint interchangeably', () => {
    const a = new FastRNG(7);
    const b = new FastRNG(7n);
    for (let i = 0; i < 8; i++) assert.equal(a.unit(), b.unit());
  });

  it('still remaps zero away from the xorshift fixed point', () => {
    const z = new FastRNG(0);
    assert.notEqual(z.unit(), 0);
    const zb = new FastRNG(0n);
    assert.equal(new FastRNG(0).unit(), zb.unit());
  });

  it('blockSeed takes a numeric base', () => {
    assert.equal(blockSeed(7, 3), blockSeed(7n, 3));
  });
});
